import Image from "next/image";
import { Toggle } from "@/components/toggle";
import { Navigation } from "@/components/navbar";
import { auth } from "@/auth";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { getUserDashboard } from "@/server-actions/dashboard/getUserDashboard";
import { Organization } from "@prisma/client";
import { Button } from "@/components/ui/button";
import { Plus, ArrowUpRight, SquareArrowOutUpRight } from "lucide-react";
import { JobCard } from "@/components/job-card";
import { CreateJobButton } from "@/components/create-job";
import Link from "next/link";
import { motion } from "framer-motion"
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import EditOrganization from "@/components/edit-organization";
import { Card, CardContent } from "@/components/ui/card";
import { StatisticalCard } from "@/components/statistical-card";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await auth();
  if(!session) { redirect('/auth') }
  if(session.user?.firstTimeUser === true) { redirect('/onboarding') }
  const organization = await getUserDashboard();
  if(organization === null) { redirect('/onboarding' ) }
  return (
        <>
        <div className="flex justify-between items-center w-full">
        <h1 className="font-bold text-3xl tracking-tight">Overview</h1>
        <Button size={"sm"} variant={"expandIcon"} asChild Icon={SquareArrowOutUpRight} iconPlacement="right" className=" w-36 bg-blue-600 text-white hover:bg-blue-700 duration-200">
        <Link target="_blank" href={`https://${organization.slug}.${process.env.NEXT_URL}`}>
        Preview
        </Link>
        </Button>
        </div>
        <div className="flex sm:flex-row flex-col gap-2">
          <div className="relative w-full">
          <StatisticalCard name="Active Jobs" number={organization.jobs.length} />
          </div>
          <div className="relative w-full">
          <StatisticalCard name="Inactive Jobs" number={0} />
          </div>
          <div className="relative w-full">
          <StatisticalCard name="Total Applicants" number={0} />
          </div>
        </div>
        <div className="space-y-2">
        <h1 className="font-bold text-3xl tracking-tight">Recent Jobs</h1>
        </div>
        </>
  );
}
