import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Settings",
    description: "Generated by create next app",
};

export default async function Page() {
    return (
        <>
        Settings Page.
        </>
    )
}