import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Jobs",
    description: "Generated by create next app",
};

export default function Layout() {
    return (
        <></>
    )
}