import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Jobs",
    description: "Generated by create next app",
};

export default function Loading() {
    return (
        <>
        <h1 className="font-bold text-3xl">Jobs</h1>
        <p>Loading your jobs</p>
        </>
    )
}