import Image from "next/image";
import { Toggle } from "@/components/toggle";
import { Navigation } from "@/components/navbar";
import { auth } from "@/auth";
import { Metadata } from "next";
import { redirect } from "next/navigation";
import { getUserDashboard } from "@/server-actions/dashboard/getUserDashboard";
import { Job, Organization } from "@prisma/client";
import { JobCard } from "@/components/job-card";

export const metadata: Metadata = {
  title: "Jobs",
  description: "Generated by create next app",
};


export default async function Page() {
  const session = await auth();
  if(!session) { redirect('/') }
  if(session.user?.firstTimeUser === true) { redirect('/onboarding') }
  const organization= await getUserDashboard();
  return (
   <>
   <h1 className="font-bold text-3xl">Jobs</h1>
   <div className="flex">
   {organization?.jobs.map((job:Job) => {
            return (
                <>
                <JobCard id={job.id} title={job.title} type={job.type} content={job.content} organizationId={job.organizationId}/>
                </>
            )
    })}
   </div>
   </>
  );
}
