import Image from "next/image";
import { Toggle } from "@/components/toggle";
import { Navigation } from "@/components/navbar";
import { auth } from "@/auth";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await auth();
  return (
   <>
   <h1 className="font-bold text-3xl">Overview</h1>
   </>
  );
}
