import { Metadata } from "next";
import { Separator } from "@/components/ui/separator";
import EditOrganization from "@/components/edit-organization";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { getUserBilling } from "@/server-actions/billing/get-user-billing";
import { getUserDashboard } from "@/server-actions/dashboard/getUserDashboard";
import { Organization } from "@prisma/client";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = {
  title: "Billing",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await auth();
  if(!session) { redirect('/auth') }
  if(session.user?.firstTimeUser === true) { redirect('/onboarding') }
  const user = await getUserBilling();
    return (
        <>
        <div className="space-y-0.5">
          <h2 className="text-3xl font-bold tracking-tight">Billing</h2>
          <p className="text-muted-foreground">
            Manage your account settings and set e-mail preferences.
          </p>
        </div>
        <Separator className=""/>
        <div className="space-y-4">
          <div className="w-full border rounded-lg p-6 space-y-6">
            <div>
            <h1 className="font-bold text-xl">Subscription Plan</h1>
            </div>
            <div className="flex justify-between items-center w-full">
              <h1 className="font-medium text-base text-muted-foreground">{user?.isPremium ? "Premium Plan" : "Free Plan"}</h1>
              {
                user?.isPremium 
                ? <Button variant={"outline"} className="bg-inherit" asChild>
                  <Link target="_blank" href={`https://app.gumroad.com/subscriptions/${user.subscription_id}/manage`}>
                  Manage Plan
                  </Link>
                  </Button>
                : <Link target="_blank" href={`https://heliup.gumroad.com/l/heliup?email=${session.user?.email}&custom_field=${session.user?.id}`}>
                  <Button variant={"outline"} className="bg-inherit">Upgrade to Premium</Button>
                  </Link>
              }
            </div>
          </div>
          {
            user?.isPremium 
            ? 
            <>
            <div className="w-full border rounded-lg p-6 space-y-6">
            <div>
            <h1 className="font-bold text-xl">Cancel Subscription</h1>
            </div>
            <div className="space-y-4">
            <h1 className="font-medium text-base text-muted-foreground">If you wish to cancel your subscription, please click the button below. Note that you will lose all the benefits of your current plan.</h1>
            <Button variant={"outline"} className="bg-inherit" asChild>
              <Link href={`https://app.gumroad.com/subscriptions/${user.subscription_id}/manage`}>
              Cancel Subscription
              </Link>
              </Button>
            </div>
            </div>
            </>
            : 
            <>
            </>
          }
        </div>
        </>
    )
}