import { Metadata } from "next";
import { Separator } from "@/components/ui/separator";
import EditOrganization from "@/components/edit-organization";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { getUserBilling } from "@/server-actions/billing/get-user-billing";
import { getUserDashboard } from "@/server-actions/dashboard/getUserDashboard";
import { Organization } from "@prisma/client";

export const metadata: Metadata = {
  title: "Billing",
  description: "Generated by create next app",
};

export default async function Page() {
  const session = await auth();
  if(!session) { redirect('/auth') }
  if(session.user?.firstTimeUser === true) { redirect('/onboarding') }
  const user = await getUserBilling();
    return (
        <>
        <div className="space-y-0.5">
          <h2 className="text-3xl font-bold tracking-tight">Billing</h2>
          <p className="text-muted-foreground">
            Manage your account settings and set e-mail preferences.
          </p>
        </div>
        <Separator className=""/>
        <div>
          <h1>You are currntly subscribed to : {user?.isPremium ? "Premium Plan" : "Free Plan"}</h1>
        </div>
        </>
    )
}