import { Metadata } from "next"

export const metadata: Metadata = {
    title: "Applicants",
    description: "Generated by create next app",
  };

export default function Loading() {
    return (
        <>
        Loading skeleton should appear here.
        </>
    )
}